services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: pcc-cas-db
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Kusopass
      MYSQL_DATABASE: pcc_cas
      TZ: "Asia/Tokyo"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql

  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "mysql"
    ports:
      - 8080:8080
    restart: always
    tty: true
    volumes:
      - ./running:/PCC_CAS